- assert:
    that: eqm_state == 'present'
- assert:
    that: ansible_distribution == 'Ubuntu'
- assert:
    that: ansible_distribution_version == '16.04'
- assert:
    that: ansible_service_mgr == 'systemd'

- name: copy eqm executable
  copy:
    src: eqm_ubuntu_16
    dest: "{{ eqm_exe }}"
    owner: root
    group: root
    mode: 0700

- name: create eqm template service
  template:
    src: eqm@.service.jinja2
    dest: /etc/systemd/system/{{ eqm_service }}@.service
    owner: root
    group: root
    mode: 0644
  notify: restart eqm

- name: enable/disable eqm services
  systemd:
    name: "{{ eqm_service }}@{{ item.gpu }}"
    enabled: "{{ item.state|default('present') == 'present' }}"
    daemon_reload: yes
  with_items: "{{ eqm_cuda_devices }}"

- name: stop absent eqm services
  systemd:
    name: "{{ eqm_service }}@{{ item.gpu }}"
    state: stopped
  when: item.state|default('present') == 'absent'
  with_items: "{{ eqm_cuda_devices }}"

- meta: flush_handlers

- name: start present eqm services
  systemd:
    name: "{{ eqm_service }}@{{ item.gpu }}"
    state: started
  when: item.state|default('present') == 'present'
  with_items: "{{ eqm_cuda_devices }}"
