- assert:
    that: ccminer_exe_state in ('present', 'absent')
- assert:
    that: ansible_distribution == 'Ubuntu'
- assert:
    that: ansible_distribution_version == '18.04'
- assert:
    that: ansible_service_mgr == 'systemd'

- include_tasks: "{{ ccminer_exe_state }}.yml"
