- name: create ccminer install directory
  file:
    dest: "{{ ccminer_exe_install_dir }}"
    state: 'directory'
    mode: 0755

- name: install ccminer dependencies
  apt: name={{ item }} state=present
  with_items: "{{ ccminer_exe_apt_dependencies }}"

- name: download ccminer src
  git:
    repo: "{{ ccminer_exe_git_clone_url }}"
    dest: "{{ ccminer_exe_install_dir }}"
    version: "{{ ccminer_exe_git_commit_hash }}"
    force: yes
  register: ccminer_coin_clone_result

- name: delete ccminer if necessary for rebuild
  file:
    path: "{{ ccminer_exe_binary }}"
    state: absent
  when: ccminer_coin_clone_result.changed

- name: update alternatives to link gcc-5 to gcc
  alternatives:
    name: gcc
    link: /usr/bin/gcc
    path: /usr/bin/gcc-5
    priority: 1

- name: build ccminer
  command: ./build.sh
  args:
    chdir: "{{ ccminer_exe_install_dir }}"
    creates: "{{ ccminer_exe_binary }}"
