- name: set up connection before gathering facts
  hosts: all
  gather_facts: no
  roles:
    - ansible/setup/connection
  tags:
    - always

- name: connect and gather facts
  hosts: all
  tasks:
    - name: node summary
      debug:
        msg: >-
          {{ ansible_all_ipv4_addresses | join(' ') }},
          {{ ansible_distribution }} {{ ansible_distribution_version }},
          {{ ansible_processor_vcpus }} CPU(s),
          {{ ansible_memtotal_mb }} MB memory
  tags:
    - always
    - connect

- name: bootstrap connection credentials
  hosts: all
  roles:
    - role: ansible/setup/bootstrap
      when: bootstrap|default(false)|bool
      tags:
        - bootstrap

- name: set up ansible environment on remote
  hosts: all
  roles:
    - ansible/remote
  tags:
    - always
    - base-setup  # not part of base tag since really a setup task but needs apt mirrors, etc. from previous base plays
    - ansible-remote

- name: common
  hosts: all
  roles:
    - common/essential
  tags:
    - always
    - base
    - common-essential

- hosts: all
  roles:
    - role: common/nonessential
      tags:
        - common-nonessential
        - common

- hosts: hs110-stats
  roles:
    - role: generic/hs110-stats
      tags:
        - hs110-stats

- hosts: coin-stats
  roles:
    - role: generic/coin-stats
      coin_stats_coinmarketcap_ids: "{{ coinmarketcap_ids.split(',') }}"
      tags:
        - coin-stats

- hosts: nicehash-stats
  roles:
    - role: mining/nicehash-stats
      nicehash_api_key: "{{ vault_nicehash_api_key }}"
      nicehash_api_secret: "{{ vault_nicehash_api_secret }}"
      nicehash_organization_id: "{{ vault_nicehash_organization_id }}"
      tags:
        - nicehash-stats

- hosts: nvidia-miner
  roles:
#    - role: galaxy/nvidia-drivers
#      nvidia_driver_package_version: "430.14"
#      tags:
#        - nvidia-drivers
#        - nvidia-miner
    - role: mining/nvidia-smi-stats
      tags:
        - nvidia-smi-stats
        - nvidia-miner
    - role: mining/nvidia-overclock
      tags:
        - nvidia-overclock
        - nvidia-miner

- hosts: ethereum
  roles:
    - role: mining/ethminer-coin
      ethminer_coin_state: "{{ ethereum_state|default('present') }}"
      ethminer_coin_name: ethereum
      ethminer_coin_pool: "{{ ethereum_pool }}"
      ethminer_coin_gpu_type: "{{ ethereum_gpu_type }}"
      ethminer_coin_cuda_devices: "{{ ethereum_cuda_devices|default([]) }}"
      ethminer_coin_api_port: "{{ ethereum_api_port|default('0') }}"
      ethminer_coin_cuda_block_size: "{{ ethereum_cuda_block_size|default(128)|int }}"
      ethminer_coin_cuda_grid_size: "{{ ethereum_cuda_grid_size|default(8192)|int }}"
      ethminer_coin_cuda_streams: "{{ ethereum_cuda_streams|default(2)|int }}"
      ethminer_coin_cuda_schedule: "{{ ethereum_cuda_schedule|default('auto') }}"
      ethminer_coin_cuda_parallel_hash: "{{ ethereum_cuda_parallel_hash|default(4)|int }}"
      ethminer_coin_overclock_at_start: "{{ ethereum_overclock_at_start|default('no')|bool }}"
      tags:
        - ethminer
        - ethereum
