ccminer_coin_state: present
ccminer_coin_service: ccminer-{{ ccminer_coin_name }}
ccminer_coin_config_dir: /etc/ccminer/conf.d

ccminer_coin_gpu_devices: []
ccminer_coin_api_bind: 0
ccminer_coin_api_remote: no
ccminer_coin_intensity: auto
ccminer_coin_cuda_schedule: auto
ccminer_coin_cpu_priority: 3

ccminer_coin_overclock_at_start: no
ccminer_coin_overclock_command: "{{ gpu_overclock_vars[ccminer_coin_gpu_type].exe.multi_gpus }} {{ ccminer_coin_gpu_devices|join(',') }} {{ gpu_overclock_vars[ccminer_coin_gpu_type].algorithms[ccminer_coin_supported_coins[ccminer_coin_name].algorithm] }}"

ccminer_coin_supported_coins:
  vertcoin:
    algorithm: lyra2v2
    pools:
      coinotron:
        url: stratum+tcp://coinotron.com:3340
        user: gitlit.peter
        pass: spaghetti14
      give-me-coins:
        url: stratum+tcp://vtc.give-me-coins.com:3337
        user: gitlit.bob
        pass: spaghetti14
  monacoin:
    algorithm: lyra2v2
    pools:
      suprnova:
        url: stratum+tcp://mona.suprnova.cc:2995
        user: gitlit.billy
        pass: spaghetti14
      poolmining:
        url: stratum+tcp://mona.poolmining.org:3092
        # TODO: make sure monacoin_wallet is passed
        user: "{{ monacoin_wallet }}"
        pass: d=8
  vivocoin:
    algorithm: neoscrypt
    pools:
      altminer:
        url: stratum+tcp://eu1.altminer.net:10001
        # TODO: make sure vivocoin_wallet is passed
        user: "{{ vivocoin_wallet }}"
        pass: c=VIVO
  zcash:
    algorithm: equihash
    pools:
      flypool:
        url: stratum+tcp://us1-zcash.flypool.org:3333
        # TODO: make sure zcash_wallet is passed
        user: "{{ zcash_wallet }}"
        pass:


# must set:
# ccminer_coin_name
# ccminer_coin_pool
# ccminer_coin_gpu_type
# ccminer_coin_gpu_devices
