ansible_surrogate_user: ansible
vault_dir_name: vault

pip_default_index_url: https://pypi.python.org/simple
pip_version_spec:
setuptools_version_spec:
virtualenv_version_spec:

pki_tls_ca_bundle: /etc/ssl/certs/ca-certificates.crt
pki_tls_dir: /etc/ssl
pki_tls_private_dir: /etc/ssl/private
pki_tls_private_group: ssl-cert

influxdb_host: "{{ vault_influxdb_host }}"
influxdb_username: "{{ vault_influxdb_username }}"
influxdb_password: "{{ vault_influxdb_password }}"
influxdb_scheme: https
influxdb_port: 443
influxdb_url: "{{ influxdb_scheme }}://{{ influxdb_host }}:{{ influxdb_port }}"
influxdb_database_name: telegraf

postfix_relayhost: smtp-relay.gmail.com
postfix_relayhost_port: 587
postfix_sasl_user: "{{ vault_postfix_sasl_user }}"
postfix_sasl_password: "{{ vault_postfix_sasl_password }}"

vnc_password: "{{ vault_vnc_password }}"

alert_email_address: "{{ vault_alert_email_address }}"

gpu_overclock_vars:
  nvidia-gtx1070:
    exe:
      all_gpus: "{{ nvidia_overclock_exe }}"
      multi_gpus: "{{ nvidia_overclock_exe }} -i"
    algorithms:
      daggerhashimoto: "-l 125 -p 1 -c 150 -m 650 -f auto"
      equihash: "-l 100 -p 1 -c 0 -m 700 -f auto"
      lyra2v2: "-l 100 -p 1 -c 0 -m 700 -f auto"
      neoscrypt: "-l 100 -p 1 -c 0 -m 700 -f auto"
      x16r: "-l 117 -p 1 -c 100 -m 400 -f auto"
