ansible_surrogate_user: ansible
vault_dir_name: vault

pip_default_index_url: https://pypi.python.org/simple
pip_version_spec:
setuptools_version_spec:
virtualenv_version_spec:

pki_tls_ca_bundle: /etc/ssl/certs/ca-certificates.crt
pki_tls_dir: /etc/ssl
pki_tls_private_dir: /etc/ssl/private
pki_tls_private_group: ssl-cert

influxdb_host: 192.168.1.3
influxdb_username: "{{ vault_influxdb_username }}"
influxdb_password: "{{ vault_influxdb_password }}"
influxdb_scheme: http
influxdb_port: 8086
influxdb_url: "{{ influxdb_scheme }}://{{ influxdb_host }}:{{ influxdb_port }}"
influxdb_database_name: telegraf
telegraf_udp_host: 127.0.0.1
telegraf_udp_port: 8094

postfix_relayhost: smtp-relay.gmail.com
postfix_relayhost_port: 587
postfix_sasl_user: "{{ vault_postfix_sasl_user }}"
postfix_sasl_password: "{{ vault_postfix_sasl_password }}"

vnc_password: "{{ vault_vnc_password }}"

sudoers: []
alert_email_address: "{{ vault_alert_email_address }}"

gpu_overclock_vars:
  nvidia-gtx1070:
    exe:
      all_gpus: "{{ nvidia_overclock_exe }}"
      multi_gpus: "{{ nvidia_overclock_exe }} -i"
    algorithms:
      neoscrypt: "-l 100 -p 1 -c 0 -m 700 -f auto"
      equihash: "-l 100 -p 1 -c 0 -m 700 -f auto"
      lyra2v2: "-l 100 -p 1 -c 0 -m 700 -f auto"
      daggerhashimoto: "-l 100 -p 1 -c 0 -m 700 -f auto"
