- assert:
    that: ethminer_coin_state in ('present', 'absent')
- assert:
    that: ansible_distribution == 'Ubuntu'
- assert:
    that: ansible_distribution_version == '16.04'
- assert:
    that: ansible_service_mgr == 'systemd'

- include_tasks: absent.yml
  when: ethminer_coin_state == 'absent' or ethminer_coin_cuda_devices|length == 0

- include_tasks: present.yml
  when:
    - ethminer_coin_state == 'present'
    - ethminer_coin_cuda_devices|length > 0
