- name: create {{ ethminer_coin_service }} service
  template:
    src: ethminer.service.jinja2
    dest: /etc/systemd/system/{{ ethminer_coin_service }}.service
    owner: root
    group: root
    mode: 0644
  notify: restart ethminer

- name: enable {{ ethminer_coin_service }} service
  systemd:
    name: "{{ ethminer_coin_service }}"
    enabled: yes
    daemon_reload: yes

- meta: flush_handlers

- name: start {{ ethminer_coin_service }} service
  systemd:
    name: "{{ ethminer_coin_service }}"
    state: started
