# this role is ONLY for tasks ESSENTIAL to ALL hosts

- name: update apt cache
  apt: update_cache=yes
  register: result
  until: result is succeeded
  changed_when: False

- name: update time zone database
  apt: name=tzdata state=latest
  notify: restart cron

- name: add sudoers
  template:
    src: sudoers.d/ansible-managed.jinja2
    dest: /etc/sudoers.d/ansible-managed
    owner: root
    group: root
    mode: 0440
    validate: 'visudo -cf %s'

- name: set time zone
  timezone: name={{ timezone }}
  notify: restart cron
  when: timezone != ''

- meta: flush_handlers
