---
- name: install dependencies (apt)
  become: yes
  apt:
    name:
      - lightdm
      - libglib2.0-bin
    state: present
  when: ansible_pkg_mgr == 'apt'

- name: write LightDM configuration
  become: yes
  template:
    src: lightdm.conf.j2
    dest: '{{ lightdm_conf_directory }}/{{ lightdm_overide_filename }}'
    owner: root
    group: root
    mode: 'u=rw,go=r'
  register: lightdm_config

- name: apply glib schemas changes
  tags:
    # Suppress warning: [ANSIBLE0016] Tasks that run when changed should likely be handlers
    # Since the command is invoked with an argument that is role specific it
    # doesn't make sense to use a handler, which are global to the playbook.
    - skip_ansible_lint
  become: yes
  command: '/usr/bin/glib-compile-schemas {{ lightdm_glib_schemas_directory }}'
  when: lightdm_config.changed
