- assert:
    that: hs110_stats_state in ('present', 'absent')

- when: hs110_stats_state == 'present'
  block:
    - name: create hs110-stats script dir
      file:
        path: "{{ hs110_stats_script_path|dirname }}"
        owner: root
        group: root
        mode: 0755
        state: directory

    - name: copy hs110-stats script
      copy:
        src: hs110-stats
        dest: "{{ hs110_stats_script_path }}"
        owner: root
        group: root
        mode: 0755

- include_role:
    name: generic/telegraf/plugin
  vars:
    telegraf_plugin_conf_src: telegraf.conf.jinja2
    telegraf_plugin_conf: hs110-stats.conf
    telegraf_plugin_state: "{{ hs110_stats_state }}"

- name: delete hs110-stats script
  file:
    path: "{{ hs110_stats_dir }}"
    state: absent
  when: hs110_stats_state == 'absent'
