- name: create ethminer install directory
  file:
    dest: "{{ ethminer_exe_install_dir }}"
    state: 'directory'
    mode: 0755

- name: install ethminer dependencies
  apt:
    name: "{{ ethminer_exe_apt_dependencies }}"
    state: present

- name: download ethminer src
  git:
    repo: "{{ ethminer_exe_git_clone_url }}"
    dest: "{{ ethminer_exe_install_dir }}"
    version: "{{ ethminer_exe_git_commit_hash }}"
    force: yes
  changed_when: ethminer_git_clone.before != ethminer_git_clone.after
  register: ethminer_git_clone

- name: delete ethminer if necessary for rebuild
  file:
    path: "{{ ethminer_exe_build_dir }}"
    state: absent
  when: ethminer_git_clone.changed

- name: create ethminer build directory
  file:
    dest: "{{ ethminer_exe_build_dir }}"
    state: 'directory'
    mode: 0755

- name: configure ethminer
  command: cmake .. -DETHASHCUDA=ON -DETHASHCL=OFF -DAPICORE=ON -DETHDBUS=ON -DBINKERN=ON -DUSE_SYS_OPENCL=OFF
  args:
    chdir: "{{ ethminer_exe_build_dir }}"
    creates: "{{ ethminer_exe_build_dir }}/CMakeCache.txt"

- name: build ethminer cmake
  command: cmake --build .
  args:
    chdir: "{{ ethminer_exe_build_dir }}"
    creates: "{{ ethminer_exe_binary }}"
