- assert:
    that: nicehash_stats_state in ('present', 'absent')

- name: copy nicehash-worker-stats script
  copy:
    src: nicehash-worker-stats
    dest: "{{ nicehash_stats_script_install_dir }}/nicehash-worker-stats"
    owner: root
    group: root
    mode: 0755
  when: nicehash_stats_state == 'present'

- name: delete nicehash-worker-stats script
  file:
    path: "{{ nicehash_stats_script_install_dir }}/nicehash-worker-stats"
    state: absent
  when: nicehash_stats_state == 'absent'

- include_role:
    name: generic/telegraf/plugin
  vars:
      telegraf_plugin_conf_src: nicehash-worker-stats.conf.jinja2
      telegraf_plugin_conf: nicehash-worker-stats.conf
      telegraf_plugin_state: "{{ nicehash_stats_state }}"

- name: copy nicehash-wallet-stats script
  copy:
    src: nicehash-wallet-stats
    dest: "{{ nicehash_stats_script_install_dir }}/nicehash-wallet-stats"
    owner: root
    group: root
    mode: 0755
  when: nicehash_stats_state == 'present'

- name: delete nicehash-wallet-stats script
  file:
    path: "{{ nicehash_stats_script_install_dir }}/nicehash-wallet-stats"
    state: absent
  when: nicehash_stats_state == 'absent'

- include_role:
    name: generic/telegraf/plugin
  vars:
      telegraf_plugin_conf_src: nicehash-wallet-stats.conf.jinja2
      telegraf_plugin_conf: nicehash-wallet-stats.conf
      telegraf_plugin_state: "{{ nicehash_stats_state }}"
