- assert:
    that: nicehash_stats_state in ('present', 'absent')

- when: nicehash_stats_state == 'present'
  block:
    - name: install python dependencies
      pip:
        virtualenv: "{{ nicehash_stats_virtualenv_path }}"
        name:
          - requests
          - click
        extra_args: --upgrade-strategy only-if-needed
        state: latest

    - name: copy nicehash-stats script
      template:
        src: nicehash-stats.jinja2
        dest: "{{ nicehash_stats_script_install_dir }}/nicehash-stats"
        owner: root
        group: root
        mode: 0755

- name: delete nicehash-stats script
  file:
    path: "{{ nicehash_stats_script_install_dir }}/nicehash-stats"
    state: absent
  when: nicehash_stats_state == 'absent'

- include_role:
    name: generic/telegraf/plugin
  vars:
    telegraf_plugin_conf_src: nicehash-stats.conf.jinja2
    telegraf_plugin_conf: nicehash-stats.conf
    telegraf_plugin_state: "{{ nicehash_stats_state }}"
