- name: additional authorized ssh keys
  authorized_key:
    user: "{{ item.user }}"
    key: "{{ item.key }}"
    state: "{{ item.state|default('present') }}"
  with_items: "{{ authorized_keys }}"

- name: update time zone database
  apt:
    name: tzdata
    state: latest
  notify: restart cron

- name: set time zone
  timezone:
    name: "{{ timezone }}"
  notify: restart cron
  when: timezone != ''

- name: update apt cache
  apt:
    update_cache: yes
  register: result
  until: result is succeeded
  changed_when: False

- name: install common packages
  apt:
    name: "{{ common_pkgs.apt }}"
    state: latest

- meta: flush_handlers
