ansible_host: 192.168.1.8

nut_ups_devices:
  - |
    [wan-ups]
        driver = usbhid-ups
        port = auto
        desc = "WAN UPS"
nut_ups_monitors:
  - "MONITOR wan-ups@localhost 1 {{ nut_user_master_name }} {{ nut_user_master_password }} master"
nut_stats_target: wan-ups
