- assert:
    that: zcash_wallet_state in ('present', 'absent')
- assert:
    that: ansible_service_mgr == 'systemd'

- include_tasks: absent.yml
  when: zcash_wallet_state == 'absent'

- name: install zcash dependencies
  apt:
    name: "{{ zcash_wallet_apt_dependencies }}"
    state: present

- name: add/remove zcash gpg signing key
  apt_key:
    url: https://apt.z.cash/zcash.asc
    state: "{{ zcash_wallet_state }}"

- name: add/remove zcash repository
  apt_repository:
    repo: 'deb [arch=amd64] https://apt.z.cash/ jessie main'
    state: "{{ zcash_wallet_state }}"

- name: install/uninstall zcash wallet
  apt:
    name: zcash
    state: "{{ zcash_wallet_state }}"

- include_tasks: present.yml
  when: zcash_wallet_state == 'present'
