- assert:
    that: zcash_wallet_state in ('present',)
- assert:
    that: ansible_service_mgr == 'systemd'

- name: install zcash dependencies
  apt:
    name: "{{ zcash_wallet_apt_dependencies }}"
    state: present

- name: add zcash gpg signing key
  apt_key:
    url: https://apt.z.cash/zcash.asc
    state: "{{ zcash_wallet_state }}"

- name: add zcash repository
  apt_repository:
    repo: 'deb [arch=amd64] https://apt.z.cash/ jessie main'
    state: "{{ zcash_wallet_state }}"

- name: install zcash wallet
  apt: name=zcash state={{ zcash_wallet_state }}

- name: fetch zcash params
  command: "{{ zcash_wallet_fetch_params }}"
  become: yes
  become_user: "{{ zcash_wallet_system_user }}"
  register: zcash_fetch_params_result
  changed_when: "'https://z.cash/downloads/sprout-proving.key' in zcash_fetch_params_result.stdout"

- name: create zcash config directory
  file:
    dest: "{{ zcash_wallet_config_dir }}"
    state: directory
    mode: 0755

- name: create zcash config
  template:
    src: zcash.conf.jinja2
    dest: "{{ zcash_wallet_config_dir }}/zcash.conf"
    owner: "{{ zcash_wallet_system_user }}"
    group: "{{ zcash_wallet_system_user }}"
    mode: 0600
  notify: restart zcashd

- name: create zcashd service
  template:
    src: zcashd.service.jinja2
    dest: /etc/systemd/system/{{ zcash_wallet_service }}.service
    owner: root
    group: root
    mode: 0644
  notify: restart zcashd

- name: enable {{ zcash_wallet_service }} service
  systemd:
    name: "{{ zcash_wallet_service }}"
    enabled: yes
    daemon_reload: yes

- meta: flush_handlers

- name: start {{ zcash_wallet_service }} service
  systemd:
    name: "{{ zcash_wallet_service }}"
    state: started
