- import_playbook: include-base.yml base_hosts=all

- hosts: all
  roles:
    - role: common/nonessential
      tags:
        - common-nonessential
        - common

- hosts: hs110-stats
  roles:
    - role: generic/hs110-stats
      tags:
        - hs110-stats

- hosts: nvidia-miner
  roles:
#    - role: galaxy/nvidia-cuda
#      gpu: True
#      tags:
#        - nvidia-cuda
#        - nvidia-miner
    - role: mining/nvidia-smi-stats
      tags:
        - nvidia-smi-stats
        - nvidia-miner
    - role: mining/nvidia-overclock
      tags:
        - nvidia-overclock
        - nvidia-miner

- hosts: nicehash-miner
  roles:
    - role: mining/nicehash-stats
      nicehash_api_id: "{{ vault_nicehash_api_id }}"
      nicehash_api_key: "{{ vault_nicehash_api_key_read_only }}"
      nicehash_stats_state: "{{ nicehash_miner_state }}"
      tags:
        - nicehash-stats
        - nicehash-miner
    - role: mining/eqm-miner
      eqm_worker_name: "{{ nicehash_worker_name }}"
      eqm_bitcoin_address: "{{ nicehash_bitcoin_address }}"
      eqm_overclock_command: "{{ nvidia_overclock_exe }} -i %i -l {{ nvidia_power_limit }} -p {{ nvidia_persistence_mode }} -c {{ nvidia_gpu_clock_offset }} -m {{ nvidia_mem_clock_offset }} -f {{ nvidia_fan_speed }}"
      eqm_state: "{{ nicehash_miner_state }}"
      tags:
        - eqm-miner
        - nicehash-miner

- hosts: vertcoin
  roles:
    - role: mining/ccminer
      ccminer_state: "{{ vertcoin_state|default('present') }}"
      ccminer_coin: vertcoin
      ccminer_pool: "{{ vertcoin_pool }}"
      ccminer_gpu_type: "{{ vertcoin_gpu_type }}"
      ccminer_gpu_devices: "{{ vertcoin_gpu_devices|default([]) }}"
      ccminer_api_bind: "{{ vertcoin_api_bind|default('0') }}"
      ccminer_api_remote: "{{ vertcoin_api_remote|default('no')|bool }}"
      ccminer_intensity: "{{ vertcoin_intensity|default('auto') }}"
      ccminer_cuda_schedule: "{{ vertcoin_cuda_schedule|default('auto') }}"
      ccminer_cpu_priority: "{{ vertcoin_cpu_priority|default(3)|int }}"
      ccminer_overclock_at_start: "{{ vertcoin_overclock_at_start|default('no')|bool }}"
      tags:
        - vertcoin
        - ccminer

- hosts: monacoin
  roles:
    - role: mining/ccminer
      ccminer_state: "{{ monacoin_state|default('present') }}"
      ccminer_coin: monacoin
      ccminer_pool: "{{ monacoin_pool }}"
      ccminer_gpu_type: "{{ monacoin_gpu_type }}"
      ccminer_gpu_devices: "{{ monacoin_gpu_devices|default([]) }}"
      ccminer_api_bind: "{{ monacoin_api_bind|default('0') }}"
      ccminer_api_remote: "{{ monacoin_api_remote|default('no')|bool }}"
      ccminer_intensity: "{{ monacoin_intensity|default('auto') }}"
      ccminer_cuda_schedule: "{{ monacoin_cuda_schedule|default('auto') }}"
      ccminer_cpu_priority: "{{ monacoin_cpu_priority|default(3)|int }}"
      ccminer_overclock_at_start: "{{ monacoin_overclock_at_start|default('no')|bool }}"
      tags:
        - monacoin
        - ccminer
